### ISSUE TITLE
Integrate EJS templating to HTML

### ISSUE THREAD

**Issue by xoamara** [macdhollister/skill.it#13]

**Comment by JonathanDavis22** [comment]
Hey Neri, I've completed our search/homepage and it has been pushed and merged. You can pull the current master and check it out.

I have a couple example users hardcoded. Obviously we’ll cut the second, empty the first of hardcoded user-info, and add any necessary classes or IDs we need in order to use it as a proper template to pump search yields into until they are all iterated over and displayed to the client.

Right now, the teaches/learning items are buttons. We need to decide if we want to make it so that if a user clicks one, say ‘Scuba diving’, they get back all users teaching and/or learning scuba diving, or not. If not, I can make them what Bulma calls ‘tags’, I believe. I think the text-value of a tag can be read and used by the back-end if we went that way. Mac and I think we should leave them as dummy buttons for now and think about that feature once we have the application operating.

**Comment by xoamara** [comment]
Partials rendering but need the htmlRoutes working to server the client side.
